spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: taskify
    password: password
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
